PHP/src/Cvut/Fit/BiWt1/PollBundle/Form/SurveyType.php
<?php
// src/Cvut/Fit/BiWt1/PollBundle/Form/SurveyType.php

namespace Cvut\Fit\BiWt1\PollBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class SurveyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // echo $options['data']->getTitle() ; 
        $builder->add('title', 'text', array( 'data' => isset($options['data']) ?  $options['data']->getTitle() : ''  ));
        $builder->add('description', 'textarea', array( 'data' => isset($options['data']) ?  $options['data']->getDescription() : ''  ));
        // $arrayOfQuestions = $options['data'];
        // foreach ($arrayOfQuestions as $question)
        // {
        // 	$builder->add($question->getId(), 'textarea', array( 'data' => $question->getQuestion()  ));
        // }
                // $builder->add('question', 'textarea', array( 'data' => isset($options['data']) ?  $options['data']->getQuestion() : ''  ));


    }

    public function getName()
    {
        return 'survey';
    }
}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/about.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/about.html.twig #}
{% extends '::base.html.twig' %}

{% block title %}About{% endblock%}

{% block body %}
    <header>
        <h1>About surveys</h1>
    </header>
    <article>
        <p>This site is the result of the semestral project at Web Technologies, BIE - WT1. The purpose of this project is to create a web application
        for creating, modifying and filling surveys. The site you are now looking at is a preliminary step towards the final product. It offers the possibility to
        create, save, modify surveys. On the other hand, you can answer these surveys and later look at how people voted. There are three types of questions: text questions, single choice questions and multiple choice questions. At any time you can edit a question, it's choices, delete a question or a survey. The site was developed in Symfony2 framework, that is, PHP programming language, YAML scripting language for routing. TWIG, HTML and CSS was used for layout and styling. All the data is stored in a MySQL database, accessed through Doctrine API. 
        .</p>
    </article>
{% endblock %}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/choiceQuestion.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/choiceQuestion.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}

{% block title %}{{ type|capitalize }} Choice Question{% endblock%}

{% block body %}
    <header>
        <h1>
        Create a {{ type }} choice question
        </h1>
    </header>

    <p>Write the question:</p>
    <form action="{{ path('PollBundle_choiceQuestion', { 'id' : app.request.get('id') , 'type' : app.request.get('type') }) }}" method="post" {{ form_enctype(form) }} class="blogger">
        {{ form_errors(form) }}

        {{ form_row(form.question, {'label' : 'Question*'}) }}
        <p>Write each option on a separate line:<p>
        {{ form_row(form.options, {'label' : 'Options*'}) }}


        {{ form_rest(form) }}

    <input class="blogger1" type="submit" value="Add" />
    </form>
{% endblock %}

{% block sidebar %}
    <p class="links"> <a href="{{ path('PollBundle_createSurvey') }}">Back to survey</a> </p>
{% endblock %}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/contact.html.twig
{# src/Cvut/Fit/BiWt1/PollBundleBundle/Resources/views/Page/contact.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}

{% block title %}Contact{% endblock%}

{% block body %}
    <header>
        <h1>Contact surveys</h1>
    </header>

{% if app.session.hasFlash('surveys-notice') %}
    <div class="blogger-notice">
        {{ app.session.flash('surveys-notice') }}
    </div>
{% endif %}

    <p>Want to contact Surveys Online?</p>
    <form action="{{ path('PollBundle_contact') }}" method="post" {{ form_enctype(form) }} class="blogger">
        {{ form_errors(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.email) }}
        {{ form_row(form.subject) }}
        {{ form_row(form.body) }}

        {{ form_rest(form) }}

        <input type="submit" value="Submit" />
    </form>
{% endblock %}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/createSurvey.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/createSurvey.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}

{% block title %}Create Survey{% endblock%}

{% block body %}

    <header>
        <h1>Create a survey</h1>
    </header>

    {% if app.session.hasFlash('surveys-notice') %}
    <div class="blogger-notice">
        {{ app.session.flash('surveys-notice') }}
    </div>
{% endif %}

    <p>Let's get started:</p>
    <form action="{{ path('PollBundle_createSurvey') }}" method="post" {{ form_enctype(form) }} class="blogger">
        {{ form_errors(form) }}

          

        {{ form_row(form.title, {'label' : 'Title*'}) }}       
          
        {{ form_row(form.description) }}

        <input class="blogger1" name="saveTitle" type="submit" value="Save title & description" />

        {{ form_rest(form) }}

        <p id="questions"> Questions: </p>





        {% for q in createdQuestions %}
            <p>{{ loop.index }}. {{ q.getQuestion() }} 
                <input class="deleteButton" type="button" onclick=location.href="{{ path('PollBundle_deleteQuestion', { 'id' : q.getId() }) }}" value="Delete me" />  
                <input class="modifyButton" type="button" onclick=location.href="{{ path('PollBundle_modifyQuestion', { 'id' : q.getId() }) }}" value="Modify me" />  
            </p>
            <p>
                {% if q.getType() is sameas("singleChoiceQuestion") %}
                    {% for o in q.getOptions() %}
                       <input type="radio" name={{ o.getOption() }}     disabled> {{ o.getOption() }}
                    {% endfor %}
                {% endif %}
                {% if q.getType() is sameas("multipleChoiceQuestion") %}
                    {% for o in q.getOptions() %}
                       <input type="checkbox" name={{ o.getOption() }}     disabled> {{ o.getOption() }}
                    {% endfor %}
                {% endif %}
            </p>
        {% endfor %}

    
    <section class="addQuestions">
        <input type="button" onclick=location.href="{{ path('PollBundle_textQuestion', { 'id' : "0" }) }}" value="Add a text question..." />
        <input type="button" onclick=location.href="{{ path('PollBundle_choiceQuestion', { 'id' : "0" , 'type' : "single"}) }}" value="Add single choice question..." />
        <input type="button" onclick=location.href="{{ path('PollBundle_choiceQuestion', { 'id' : "0" , 'type' : "multiple"}) }}" value="Add multiple choice question..." />
    </section class="addQuestions">

      <input class="blogger1" type="submit" value="Save survey" />
    </form>

{% endblock %}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/displaySurvey.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/displaySurvey.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}

{% block title %}Selected Survey{% endblock%}

{% block body %}
    <input class="deleteButton"  type="button" onclick=location.href="{{ path('PollBundle_deleteSurvey', { 'id' : survey.getId() }) }}" value="Delete survey" />  

    <header>
        <h1> {{ survey.getTitle() }} </h1>
    </header>
    


    <p id="description">
        {{ survey.getDescription() }}
    </p>

    <p id="questions"> Questions: </p>

    {% for q in createdQuestions %}
        <p id="question">{{ loop.index }}. {{ q.getQuestion() }} 
            {% if q.getType() is sameas("textQuestion") %}
                <input class="modifyButton"  type="button" onclick=location.href="{{ path('PollBundle_seeAnswers', { 'surveyId' : survey.getId(), 'id' : q.getId() }) }}" value="See answers" />
            {% endif %}
        </p>
        <p>
            {% if q.getType() is sameas("singleChoiceQuestion") %}
                {% for o in q.getOptions() %}
                <p class="options">
                   <input type="radio" name={{ o.getOption() }}     disabled> {{ o.getOption() }}
                  <input type="button" class="votes"  name={{ o.getOption() }} value='{{ o.getAnswers().count() }} votes'     disabled> 
                </p>
                {% endfor %}
            {% endif %}
            {% if q.getType() is sameas("multipleChoiceQuestion") %}
                {% for o in q.getOptions() %}
                <p class="options">
                    <input type="checkbox" name={{ o.getOption() }}     disabled> {{ o.getOption() }}
                    <input type="button" class="votes"  name={{ o.getOption() }} value='{{ o.getAnswers().count() }} votes'     disabled> 
                </p>
                {% endfor %}
            {% endif %}
        </p>

    {% endfor %}

{% endblock %}
{% block sidebar %}
    <p class="links"> <a href="{{ path('PollBundle_listSurveys', { 'display' : "true" }) }}">Back to list</a> </p>
    <p class="links"> <a href="{{ path('PollBundle_createSurvey') }}">Edit this survey</a> </p>
    <p class="links"> <a href="{{ path('PollBundle_takeSurvey', {'id' : survey.getId() }) }}">Take this survey</a> </p>


{% endblock%}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/index.html.twig
{# src/Cvut\Fit\BiWt1\PollBundle/Resources/views/Page/index.html.twig #}
{% extends '::base.html.twig' %}


    {% block mainActions %}
        {% if app.session.hasFlash('surveys-notice') %}
        <div class="blogger-notice">
        {{ app.session.flash('surveys-notice') }}
        </div>
        {% endif %}
   
        <section class="mainActions">
        <h4> 
            <a href="{{ path('PollBundle_createSurvey') }}">Create a survey</a> 
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <a href="{{ path('PollBundle_listSurveys', {'display' : "false"}) }}">Take a survey</a>  
        </h4>
        </section>
    {% endblock %}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/question.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/question.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}

{% block title %}Question{% endblock%}

{% block body %}
    <header>
        <h1>Question</h1>
    </header>

{% if app.session.hasFlash('question-notice') %}
    <div class="blogger-notice">
        {{ app.session.flash('question-notice') }}
    </div>
{% endif %}

    <p>Select the type of the question:</p>
    <form action="{{ path('PollBundle_question') }}" method="post" {{ form_enctype(form) }} class="blogger">


        {% for choiceFormView in form.typeOfQuestion %}
        {{ form_widget(choiceFormView) }}
        {{ form_label(choiceFormView) }}
        {% endfor %}


        <input type="submit" value="Submit" />
    </form>
{% endblock %}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/seeAnswers.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/seeAnswers.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}

{% block title %}Selected Question{% endblock%}

{% block body %}
    <header>
        <h1> {{ survey.getTitle() }} </h1>
    </header>
    


    <p id="description">
        {{ question.getQuestion() }}
    </p>

    <p id="questions"> Answers: </p>

    {% for a in answers %}
        <p id="question">{{ loop.index }}. {{ a }} 
        </p>

    {% endfor %}

{% endblock %}
{% block sidebar %}
    <p class="links"> <a href="{{ path('PollBundle_displaySurvey', { 'id' : survey.getId() }) }}">Back to survey</a> </p>


{% endblock%}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/surveysList.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/surveysList.html.twig #}
{% extends '::base.html.twig' %}

{% block title %}List of Surveys{% endblock%}

{% block body %}
    <header>
        <h1>List of Surveys</h1>
    </header>
    {% if app.session.hasFlash('surveys-notice') %}
        <div class="blogger-notice">
            {{ app.session.flash('surveys-notice') }}
        </div>
    {% endif %}
    <p>Select one:</p>
    <table id="surveys">
        <tr>
            <th>Surveys</th>
        </tr>

      {% for survey in surveys %}
        {% if display is sameas("true") %}
            <tr>
              <td
                onmouseover="this.bgColor='#F9EDA9'"
                onmouseout="this.bgColor='white'"
                onclick=location.href="{{ path('PollBundle_displaySurvey' , { 'id' : survey.getId() }) }}"
              >
                    {{ survey.getTitle() }}
              </td>
            </tr>
        {% else %}
            <tr>
              <td
                onmouseover="this.bgColor='#F9EDA9'"
                onmouseout="this.bgColor='white'"
                onclick=location.href="{{ path('PollBundle_takeSurvey' , { 'id' : survey.getId() }) }}"
              >
                    {{ survey.getTitle() }}
              </td>
            </tr>
        {% endif %}
      {% endfor %}
    </table>

{% endblock %}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/takeSurvey.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/takeSurvey.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}


{% block title %}Take Survey{% endblock%}

{% block body %}

    <header>
        <h1>{{ survey.getTitle() }}</h1>
    </header>
    {% if app.session.hasFlash('surveys-notice') %}
        <div class="blogger-notice">
            {{ app.session.flash('surveys-notice') }}
        </div>
    {% endif %}

    <p id="description">
        {{ survey.getDescription() }}
    </p>

    <p id="questions"> Questions: </p>

<form class="blogger" action="{{ path('PollBundle_takeSurvey', {'id' : survey.getId() }) }}"  method="post" >
    {% for q in createdQuestions %}
        <p id="question">{{ loop.index }}. {{ q.getQuestion() }} 
        </p>
        <p>
            {% if q.getType() is sameas("textQuestion") %}
                <input type="text" name={{ q.getId() }} >
            {% endif %}
            {% if q.getType() is sameas("singleChoiceQuestion") %}
                {% for o in q.getOptions() %}
                   <input type="radio" name={{ q.getId() }} value="{{ o.getId() }}"> {{ o.getOption() }}
                {% endfor %}
            {% endif %}
            {% if q.getType() is sameas("multipleChoiceQuestion") %}
                {% for o in q.getOptions() %}
                   <input type="checkbox" name='{{ q.getId() }}[]' value={{ o.getId() }}> {{ o.getOption() }}
                {% endfor %}
            {% endif %}
        </p>
    {% endfor %}
  <input class="blogger1" type="submit" value="Save survey" />

</form>

{% endblock %}
{% block sidebar %}
    <p class="links"> <a href="{{ path('PollBundle_listSurveys', {'display' : "false"}) }}">Back to list</a> </p>


{% endblock%}

PHP/src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/textQuestion.html.twig
{# src/Cvut/Fit/BiWt1/PollBundle/Resources/views/Page/textQuestion.html.twig #}
{% extends 'PollBundle::layout.html.twig' %}

{% block title %}Text Question{% endblock%}

{% block body %}
    <header>
        <h1>Create a text question</h1>
    </header>

    <p>Write the question:</p>
    <form action="{{ path('PollBundle_textQuestion', { 'id' : app.request.get('id') }) }}" method="post" {{ form_enctype(form) }} class="blogger">
        {{ form_errors(form) }}

        {{ form_row(form.question, {'label' : 'Question*'}) }}

        {{ form_rest(form) }}

    <input class="blogger1" type="submit" value="Add" />
    </form>

{% endblock %}
{% block sidebar %}
    <p class="links"> <a href="{{ path('PollBundle_createSurvey') }}">Back to survey</a> </p>
{% endblock %}